In [1]:
import numpy as np

### Criando vetores

In [2]:
u = np.array([1,3])
v = np.array([3,1])

### Operações com vetores

In [3]:
y = u - v
w = u + v

print(f"Vetor y: {y}\nVetor w:{w}")

Vetor y: [-2  2]
Vetor w:[4 4]


In [5]:
a = u / v
b = u * v

print(f"Vetor a:{a}\nVetor b:{b}")

Vetor a:[0.33333333 3.        ]
Vetor b:[3 3]


In [6]:
alpha = 2
escalar = alpha * u

print(f"Produto escalar de u por alpha: {escalar}")

Produto escalar de u por alpha: [2 6]


In [7]:
interno = np.dot(u, v)

print(f"Resultado produto interno: {interno}")

u3 = np.array([1,3,1])
v3 = np.array([3,1,1])

vetorial = np.cross(u3, v3)

print(f"Resultado produto vetorial: {vetorial}")

Resultado produto interno: 6
Resultado produto vetorial: [ 2  2 -8]


### Operações Básicas com Matrizes

In [8]:
I = np.array([[1,0],[0,1]])
A = np.array([[2,1],[1,2]])

In [9]:
B = A + I

print(f"Matriz A:\n{A}\nMatriz I:\n{I}\nMatriz B = A + I:\n{B}")

Matriz A:
[[2 1]
 [1 2]]
Matriz I:
[[1 0]
 [0 1]]
Matriz B = A + I:
[[3 1]
 [1 3]]


In [10]:
B = A - I

print(f"Matriz A:\n{A}\nMatriz I:\n{I}\nMatriz B = A - I:\n{B}")

Matriz A:
[[2 1]
 [1 2]]
Matriz I:
[[1 0]
 [0 1]]
Matriz B = A - I:
[[1 1]
 [1 1]]


In [11]:
C = A + u

print(f"Matriz A:\n{A}\nVetor u:{I}\nMatriz C = A + u:\n{C}")

Matriz A:
[[2 1]
 [1 2]]
Vetor u:[[1 0]
 [0 1]]
Matriz C = A + u:
[[3 4]
 [2 5]]


In [12]:
D = np.matmul(A, I)

print(f"Matriz D:\n{D}\nMatriz I:\n{I}\nMatriz D = A x I:\n{D}")

Matriz D:
[[2 1]
 [1 2]]
Matriz I:
[[1 0]
 [0 1]]
Matriz D = A x I:
[[2 1]
 [1 2]]
